name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install development files for Lua 5.2 
        run: sudo apt install --no-install-recommends lua5.2 liblua5.2-dev
      - name: Build prosody native utils (hashes.c)
        run: |
          cd prosody/util-src
          sh configure
          make

